export const categories = [
  {
    id: 1,
    title: "Computer Science",
    desc: "About computer science",
    img: "/img/categories/computer_science.png",
  },
  { id: 2, title: "Data Analyst", desc: "Working with data and insights" },
  {
    id: 3,
    title: "Full Stack Developer",
    desc: "Frontend & backend development",
  },
  { id: 4, title: "IT Support", desc: "Providing technical assistance" },
  { id: 5, title: "Cybersecurity", desc: "Protecting systems and networks" },
  { id: 6, title: "Artificial Intelligence", desc: "AI and machine learning" },
  { id: 7, title: "Cloud Computing", desc: "Managing cloud infrastructure" },
  { id: 8, title: "Game Development", desc: "Creating interactive games" },
  { id: 9, title: "Mobile Development", desc: "Building mobile apps" },
  {
    id: 10,
    title: "UI/UX Design",
    desc: "Designing user-friendly experiences",
    img: "/img/categories/ux.png",
  },
  { id: 11, title: "DevOps", desc: "Continuous integration & deployment" },
  { id: 12, title: "Blockchain", desc: "Decentralized technology & crypto" },
];

export const popularCourses = [
  {
    id: 1,
    title: "Computer Science Basics",
    desc: "Learn fundamental computer science concepts.",
    rating: 4.8,
    price: 49.99,
    discount: 20,
    popular: true,
  },
  {
    id: 2,
    title: "Data Analytics with Python",
    desc: "Analyze data using Python libraries.",
    rating: 3.9,
    price: 59.99,
    discount: 15,
    popular: true,
  },
  {
    id: 3,
    title: "Full Stack Web Development",
    desc: "Master frontend and backend development.",
    rating: 4.9,
    price: 99.99,
    discount: 25,
    popular: true,
    img: "/img/courses/full_stack.png",
  },
  {
    id: 4,
    title: "IT Support Essentials",
    desc: "Learn how to troubleshoot IT issues.",
    rating: 4.5,
    price: 39.99,
    discount: 10,
    popular: false,
  },
  {
    id: 5,
    title: "Cybersecurity Fundamentals",
    desc: "Protect networks and secure data.",
    rating: 4.8,
    price: 69.99,
    discount: 20,
    popular: true,
  },
  {
    id: 6,
    title: "Machine Learning with TensorFlow",
    desc: "Build AI models using TensorFlow.",
    rating: 4.9,
    price: 119.99,
    discount: 30,
    popular: true,
  },
  {
    id: 7,
    title: "Cloud Computing with AWS",
    desc: "Understand cloud infrastructure with AWS.",
    rating: 4.6,
    price: 79.99,
    discount: 15,
    popular: true,
  },
  {
    id: 8,
    title: "Game Development with Unity",
    desc: "Create 2D and 3D games using Unity.",
    rating: 4.7,
    price: 89.99,
    discount: 20,
    popular: true,
  },
  {
    id: 9,
    title: "Mobile App Development",
    desc: "Build Android and iOS apps.",
    rating: 4.6,
    price: 74.99,
    discount: 18,
    popular: false,
  },
  {
    id: 10,
    title: "UI/UX Design Masterclass",
    desc: "Learn to design user-friendly interfaces.",
    rating: 4.8,
    price: 64.99,
    discount: 12,
    popular: true,
  },
  {
    id: 11,
    title: "DevOps & CI/CD Pipelines",
    desc: "Automate development workflows.",
    rating: 4.7,
    price: 109.99,
    discount: 25,
    popular: true,
  },
  {
    id: 12,
    title: "Blockchain & Cryptocurrency",
    desc: "Understand blockchain technology.",
    rating: 4.6,
    price: 129.99,
    discount: 35,
    popular: false,
  },
];
